name: Flutter Web Compiler (API Mode)

on:
  workflow_dispatch:
    inputs:
      dart_code:
        description: 'Kode main.dart'
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Buat Project
        run: flutter create preview_app
          
      - name: Inject Kode
        env:
          DART_CODE: ${{ github.event.inputs.dart_code }}
        run: |
          cd preview_app
          echo "$DART_CODE" > lib/main.dart

      - name: Compile Web
        # Menggunakan renderer HTML agar mudah di-preview via Blob Iframe
        run: |
          cd preview_app
          flutter build web --release --web-renderer html

      - name: Simpan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-result
          path: preview_app/build/web/
          retention-days: 1
